wget -O Flag_of_Afghanistan.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Afghanistan.svg/36px-Flag_of_Afghanistan.png; sleep 1
wget -O Flag_of_Albania.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/36px-Flag_of_Albania.svg.png; sleep 1
wget -O Flag_of_Algeria.png http://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/36px-Flag_of_Algeria.svg.png; sleep 1
wget -O Flag_of_Andorra.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/36px-Flag_of_Andorra.svg.png; sleep 1
wget -O Flag_of_Angola.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/36px-Flag_of_Angola.svg.png; sleep 1
wget -O Flag_of_Antigua_and_Barbuda.png http://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/36px-Flag_of_Antigua_and_Barbuda.svg.png; sleep 1
wget -O Flag_of_Argentina.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/36px-Flag_of_Argentina.svg.png; sleep 1
wget -O Flag_of_Armenia.png http://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/36px-Flag_of_Armenia.svg.png; sleep 1
wget -O Flag_of_Australia.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/36px-Flag_of_Australia.svg.png; sleep 1
wget -O Flag_of_Austria.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/36px-Flag_of_Austria.svg.png; sleep 1
wget -O Flag_of_Azerbaijan.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/36px-Flag_of_Azerbaijan.svg.png; sleep 1
wget -O Flag_of_the_Bahamas.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/36px-Flag_of_the_Bahamas.svg.png; sleep 1
wget -O Flag_of_Bahrain.png http://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/36px-Flag_of_Bahrain.svg.png; sleep 1
wget -O Flag_of_Bangladesh.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/36px-Flag_of_Bangladesh.svg.png; sleep 1
wget -O Flag_of_Barbados.png http://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/36px-Flag_of_Barbados.svg.png; sleep 1
wget -O Flag_of_Belarus.png http://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/36px-Flag_of_Belarus.svg.png; sleep 1
wget -O Flag_of_Belgium.png http://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/36px-Flag_of_Belgium.svg.png; sleep 1
wget -O Flag_of_Belize.png http://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/36px-Flag_of_Belize.svg.png; sleep 1
wget -O Flag_of_Benin.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/36px-Flag_of_Benin.svg.png; sleep 1
wget -O Flag_of_Bhutan.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/36px-Flag_of_Bhutan.svg.png; sleep 1
wget -O Flag_of_Bolivia.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Bolivia_%28state%29.svg/36px-Flag_of_Bolivia_%28state%29.svg.png; sleep 1
wget -O Flag_of_Bosnia_and_Herzegovina.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/36px-Flag_of_Bosnia_and_Herzegovina.svg.png; sleep 1
wget -O Flag_of_Botswana.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/36px-Flag_of_Botswana.svg.png; sleep 1
wget -O Flag_of_Brazil.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/36px-Flag_of_Brazil.svg.png; sleep 1
wget -O Flag_of_Brunei.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/36px-Flag_of_Brunei.svg.png; sleep 1
wget -O Flag_of_Bulgaria.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/36px-Flag_of_Bulgaria.svg.png; sleep 1
wget -O Flag_of_Burkina_Faso.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/36px-Flag_of_Burkina_Faso.svg.png; sleep 1
wget -O Flag_of_Burundi.png http://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/36px-Flag_of_Burundi.svg.png; sleep 1
wget -O Flag_of_Cambodia.png http://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/36px-Flag_of_Cambodia.svg.png; sleep 1
wget -O Flag_of_Cameroon.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/36px-Flag_of_Cameroon.svg.png; sleep 1
wget -O Flag_of_Canada.png http://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/36px-Flag_of_Canada.svg.png; sleep 1
wget -O Flag_of_Cape_Verde.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/36px-Flag_of_Cape_Verde.svg.png; sleep 1
wget -O Flag_of_the_Central_African_Republic.png http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/36px-Flag_of_the_Central_African_Republic.svg.png; sleep 1
wget -O Flag_of_Chad.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/36px-Flag_of_Chad.svg.png; sleep 1
wget -O Flag_of_Chile.png http://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/36px-Flag_of_Chile.svg.png; sleep 1
wget -O Flag_of_the_Peoples_Republic_of_China.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/36px-Flag_of_the_People%27s_Republic_of_China.svg.png; sleep 1
wget -O Flag_of_Colombia.png http://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/36px-Flag_of_Colombia.svg.png; sleep 1
wget -O Flag_of_the_Comoros.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/36px-Flag_of_the_Comoros.svg.png; sleep 1
wget -O Flag_of_the_Republic_of_the_Congo.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/36px-Flag_of_the_Republic_of_the_Congo.svg.png; sleep 1
wget -O Flag_of_Costa_Rica.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/36px-Flag_of_Costa_Rica_%28state%29.svg.png; sleep 1
wget -O Flag_of_Cote_dIvoire.png http://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Flag_of_Cote_d%27Ivoire.svg/36px-Flag_of_Cote_d%27Ivoire.svg.png; sleep 1
wget -O Flag_of_Croatia.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/36px-Flag_of_Croatia.svg.png; sleep 1
wget -O Flag_of_Cuba.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/36px-Flag_of_Cuba.svg.png; sleep 1
wget -O Flag_of_Cyprus.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/36px-Flag_of_Cyprus.svg.png; sleep 1
wget -O Flag_of_the_Czech_Republic.png http://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/36px-Flag_of_the_Czech_Republic.svg.png; sleep 1
wget -O Flag_of_North_Korea.png http://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/36px-Flag_of_North_Korea.svg.png; sleep 1
wget -O Flag_of_the_Democratic_Republic_of_the_Congo.png http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/36px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png; sleep 1
wget -O Flag_of_Denmark.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/36px-Flag_of_Denmark.svg.png; sleep 1
wget -O Flag_of_Djibouti.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/36px-Flag_of_Djibouti.svg.png; sleep 1
wget -O Flag_of_Dominica.png http://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/36px-Flag_of_Dominica.svg.png; sleep 1
wget -O Flag_of_the_Dominican_Republic.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/36px-Flag_of_the_Dominican_Republic.svg.png; sleep 1
wget -O Flag_of_Ecuador.png http://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/36px-Flag_of_Ecuador.svg.png; sleep 1
wget -O Flag_of_Egypt.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/36px-Flag_of_Egypt.svg.png; sleep 1
wget -O Flag_of_El_Salvador.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/36px-Flag_of_El_Salvador.svg.png; sleep 1
wget -O Flag_of_Equatorial_Guinea.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/36px-Flag_of_Equatorial_Guinea.svg.png; sleep 1
wget -O Flag_of_Eritrea.png http://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/36px-Flag_of_Eritrea.svg.png; sleep 1
wget -O Flag_of_Estonia.png http://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/36px-Flag_of_Estonia.svg.png; sleep 1
wget -O Flag_of_Ethiopia.png http://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/36px-Flag_of_Ethiopia.svg.png; sleep 1
wget -O Flag_of_Fiji.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/36px-Flag_of_Fiji.svg.png; sleep 1
wget -O Flag_of_Finland.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/36px-Flag_of_Finland.svg.png; sleep 1
wget -O Flag_of_France.png http://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/36px-Flag_of_France.svg.png; sleep 1
wget -O Flag_of_Ghana.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/36px-Flag_of_Ghana.svg.png; sleep 1
wget -O Flag_of_The_Gambia.png http://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/36px-Flag_of_The_Gambia.svg.png; sleep 1
wget -O Flag_of_Georgia.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/36px-Flag_of_Georgia.svg.png; sleep 1
wget -O Flag_of_Gabon.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/36px-Flag_of_Gabon.svg.png; sleep 1
wget -O Flag_of_Germany.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/36px-Flag_of_Germany.svg.png; sleep 1
wget -O Flag_of_Greece.png http://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/36px-Flag_of_Greece.svg.png; sleep 1
wget -O Flag_of_Grenada.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/36px-Flag_of_Grenada.svg.png; sleep 1
wget -O Flag_of_Guatemala.png http://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/36px-Flag_of_Guatemala.svg.png; sleep 1
wget -O Flag_of_Guinea.png http://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/36px-Flag_of_Guinea.svg.png; sleep 1
wget -O Flag_of_Guinea-Bissau.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/36px-Flag_of_Guinea-Bissau.svg.png; sleep 1
wget -O Flag_of_Guyana.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/36px-Flag_of_Guyana.svg.png; sleep 1
wget -O Flag_of_Haiti.png http://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/36px-Flag_of_Haiti.svg.png; sleep 1
wget -O Flag_of_Honduras.png http://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/36px-Flag_of_Honduras.svg.png; sleep 1
wget -O Flag_of_Hungary.png http://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/36px-Flag_of_Hungary.svg.png; sleep 1
wget -O Flag_of_Iceland.png http://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/36px-Flag_of_Iceland.svg.png; sleep 1
wget -O Flag_of_India.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/36px-Flag_of_India.svg.png; sleep 1
wget -O Flag_of_Indonesia.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/36px-Flag_of_Indonesia.svg.png; sleep 1
wget -O Flag_of_Iran.png http://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/36px-Flag_of_Iran.svg.png; sleep 1
wget -O Flag_of_Iraq.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/36px-Flag_of_Iraq.svg.png; sleep 1
wget -O Flag_of_Ireland.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/36px-Flag_of_Ireland.svg.png; sleep 1
wget -O Flag_of_Israel.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/36px-Flag_of_Israel.svg.png; sleep 1
wget -O Flag_of_Italy.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/36px-Flag_of_Italy.svg.png; sleep 1
wget -O Flag_of_Jamaica.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/36px-Flag_of_Jamaica.svg.png; sleep 1
wget -O Flag_of_Japan.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/36px-Flag_of_Japan.svg.png; sleep 1
wget -O Flag_of_Jordan.png http://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/36px-Flag_of_Jordan.svg.png; sleep 1
wget -O Flag_of_Kazakhstan.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/36px-Flag_of_Kazakhstan.svg.png; sleep 1
wget -O Flag_of_Kenya.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/36px-Flag_of_Kenya.svg.png; sleep 1
wget -O Flag_of_Kiribati.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/36px-Flag_of_Kiribati.svg.png; sleep 1
wget -O Flag_of_Kuwait.png http://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/36px-Flag_of_Kuwait.svg.png; sleep 1
wget -O Flag_of_Kyrgyzstan.png http://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/36px-Flag_of_Kyrgyzstan.svg.png; sleep 1
wget -O Flag_of_Laos.png http://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/36px-Flag_of_Laos.svg.png; sleep 1
wget -O Flag_of_Latvia.png http://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/36px-Flag_of_Latvia.svg.png; sleep 1
wget -O Flag_of_Lebanon.png http://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/36px-Flag_of_Lebanon.svg.png; sleep 1
wget -O Flag_of_Lesotho.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/36px-Flag_of_Lesotho.svg.png; sleep 1
wget -O Flag_of_Liberia.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/36px-Flag_of_Liberia.svg.png; sleep 1
wget -O Flag_of_Libya.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/36px-Flag_of_Libya.svg.png; sleep 1
wget -O Flag_of_Liechtenstein.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/36px-Flag_of_Liechtenstein.svg.png; sleep 1
wget -O Flag_of_Lithuania.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/36px-Flag_of_Lithuania.svg.png; sleep 1
wget -O Flag_of_Luxembourg.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/36px-Flag_of_Luxembourg.svg.png; sleep 1
wget -O Flag_of_Madagascar.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/36px-Flag_of_Madagascar.svg.png; sleep 1
wget -O Flag_of_Malawi.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/36px-Flag_of_Malawi.svg.png; sleep 1
wget -O Flag_of_Malaysia.png http://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/36px-Flag_of_Malaysia.svg.png; sleep 1
wget -O Flag_of_Maldives.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/36px-Flag_of_Maldives.svg.png; sleep 1
wget -O Flag_of_Mali.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/36px-Flag_of_Mali.svg.png; sleep 1
wget -O Flag_of_Malta.png http://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/36px-Flag_of_Malta.svg.png; sleep 1
wget -O Flag_of_the_Marshall_Islands.png http://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_the_Marshall_Islands.svg/36px-Flag_of_the_Marshall_Islands.svg.png; sleep 1
wget -O Flag_of_Mauritania.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/36px-Flag_of_Mauritania.svg.png; sleep 1
wget -O Flag_of_Mauritius.png http://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/36px-Flag_of_Mauritius.svg.png; sleep 1
wget -O Flag_of_Mexico.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/36px-Flag_of_Mexico.svg.png; sleep 1
wget -O Flag_of_Federated_States_of_Micronesia.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Federated_States_of_Micronesia.svg/36px-Flag_of_Federated_States_of_Micronesia.svg.png; sleep 1
wget -O Flag_of_Monaco.png http://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/36px-Flag_of_Monaco.svg.png; sleep 1
wget -O Flag_of_Mongolia.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/36px-Flag_of_Mongolia.svg.png; sleep 1
wget -O Flag_of_Montenegro.png http://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/36px-Flag_of_Montenegro.svg.png; sleep 1
wget -O Flag_of_Morocco.png http://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/36px-Flag_of_Morocco.svg.png; sleep 1
wget -O Flag_of_Mozambique.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/36px-Flag_of_Mozambique.svg.png; sleep 1
wget -O Flag_of_Myanmar.png http://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/36px-Flag_of_Myanmar.svg.png; sleep 1
wget -O Flag_of_Namibia.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/36px-Flag_of_Namibia.svg.png; sleep 1
wget -O Flag_of_Nauru.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/36px-Flag_of_Nauru.svg.png; sleep 1
wget -O Flag_of_Nepal.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/16px-Flag_of_Nepal.svg.png; sleep 1
wget -O Flag_of_the_Netherlands.png http://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/36px-Flag_of_the_Netherlands.svg.png; sleep 1
wget -O Flag_of_New_Zealand.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/36px-Flag_of_New_Zealand.svg.png; sleep 1
wget -O Flag_of_Nicaragua.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/36px-Flag_of_Nicaragua.svg.png; sleep 1
wget -O Flag_of_Niger.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/36px-Flag_of_Niger.svg.png; sleep 1
wget -O Flag_of_Nigeria.png http://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/36px-Flag_of_Nigeria.svg.png; sleep 1
wget -O Flag_of_Norway.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/36px-Flag_of_Norway.svg.png; sleep 1
wget -O Flag_of_Oman.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/36px-Flag_of_Oman.svg.png; sleep 1
wget -O Flag_of_Pakistan.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/36px-Flag_of_Pakistan.svg.png; sleep 1
wget -O Flag_of_Palau.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/36px-Flag_of_Palau.svg.png; sleep 1
wget -O Flag_of_Panama.png http://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/36px-Flag_of_Panama.svg.png; sleep 1
wget -O Flag_of_Papua_New_Guinea.png http://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/36px-Flag_of_Papua_New_Guinea.svg.png; sleep 1
wget -O Flag_of_Paraguay.png http://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/36px-Flag_of_Paraguay.svg.png; sleep 1
wget -O Flag_of_Peru.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Flag_of_Peru_%28state%29.svg/36px-Flag_of_Peru_%28state%29.svg.png; sleep 1
wget -O Flag_of_the_Philippines.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/36px-Flag_of_the_Philippines.svg.png; sleep 1
wget -O Flag_of_Poland.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/36px-Flag_of_Poland.svg.png; sleep 1
wget -O Flag_of_Portugal.png http://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/36px-Flag_of_Portugal.svg.png; sleep 1
wget -O Flag_of_Qatar.png http://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/36px-Flag_of_Qatar.svg.png; sleep 1
wget -O Flag_of_South_Korea.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/36px-Flag_of_South_Korea.svg.png; sleep 1
wget -O Flag_of_Moldova.png http://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/36px-Flag_of_Moldova.svg.png; sleep 1
wget -O Flag_of_Romania.png http://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/36px-Flag_of_Romania.svg.png; sleep 1
wget -O Flag_of_Russia.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/36px-Flag_of_Russia.svg.png; sleep 1
wget -O Flag_of_Rwanda.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/36px-Flag_of_Rwanda.svg.png; sleep 1
wget -O Flag_of_Saint_Kitts_and_Nevis.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/36px-Flag_of_Saint_Kitts_and_Nevis.svg.png; sleep 1
wget -O Flag_of_Saint_Lucia.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/36px-Flag_of_Saint_Lucia.svg.png; sleep 1
wget -O Flag_of_Saint_Vincent_and_the_Grenadines.png http://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/36px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png; sleep 1
wget -O Flag_of_Samoa.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/36px-Flag_of_Samoa.svg.png; sleep 1
wget -O Flag_of_San_Marino.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/36px-Flag_of_San_Marino.svg.png; sleep 1
wget -O Flag_of_Sao_Tome_and_Principe.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Sao_Tome_and_Principe.svg/36px-Flag_of_Sao_Tome_and_Principe.svg.png; sleep 1
wget -O Flag_of_Saudi_Arabia.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/36px-Flag_of_Saudi_Arabia.svg.png; sleep 1
wget -O Flag_of_Senegal.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/36px-Flag_of_Senegal.svg.png; sleep 1
wget -O Flag_of_Serbia.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/36px-Flag_of_Serbia.svg.png; sleep 1
wget -O Flag_of_the_Seychelles.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Seychelles.svg/36px-Flag_of_the_Seychelles.svg.png; sleep 1
wget -O Flag_of_Sierra_Leone.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/36px-Flag_of_Sierra_Leone.svg.png; sleep 1
wget -O Flag_of_Singapore.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/36px-Flag_of_Singapore.svg.png; sleep 1
wget -O Flag_of_Slovakia.png http://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/36px-Flag_of_Slovakia.svg.png; sleep 1
wget -O Flag_of_Slovenia.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/36px-Flag_of_Slovenia.svg.png; sleep 1
wget -O Flag_of_the_Solomon_Islands.png http://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/36px-Flag_of_the_Solomon_Islands.svg.png; sleep 1
wget -O Flag_of_Somalia.png http://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/36px-Flag_of_Somalia.svg.png; sleep 1
wget -O Flag_of_South_Africa.png http://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/36px-Flag_of_South_Africa.svg.png; sleep 1
wget -O Flag_of_Spain.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/36px-Flag_of_Spain.svg.png; sleep 1
wget -O Flag_of_Sri_Lanka.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/36px-Flag_of_Sri_Lanka.svg.png; sleep 1
wget -O Flag_of_Sudan.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/36px-Flag_of_Sudan.svg.png; sleep 1
wget -O Flag_of_Suriname.png http://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/36px-Flag_of_Suriname.svg.png; sleep 1
wget -O Flag_of_Swaziland.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Flag_of_Swaziland.svg/36px-Flag_of_Swaziland.svg.png; sleep 1
wget -O Flag_of_Sweden.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/36px-Flag_of_Sweden.svg.png; sleep 1
wget -O Flag_of_Switzerland.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/36px-Flag_of_Switzerland.svg.png; sleep 1
wget -O Flag_of_Syria.png http://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/36px-Flag_of_Syria.svg.png; sleep 1
wget -O Flag_of_Tajikistan.png http://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/36px-Flag_of_Tajikistan.svg.png; sleep 1
wget -O Flag_of_Thailand.png http://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/36px-Flag_of_Thailand.svg.png; sleep 1
wget -O Flag_of_Macedonia.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_Macedonia.svg/36px-Flag_of_Macedonia.svg.png; sleep 1
wget -O Flag_of_East_Timor.png http://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/36px-Flag_of_East_Timor.svg.png; sleep 1
wget -O Flag_of_Togo.png http://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/36px-Flag_of_Togo.svg.png; sleep 1
wget -O Flag_of_Tonga.png http://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/36px-Flag_of_Tonga.svg.png; sleep 1
wget -O Flag_of_Trinidad_and_Tobago.png http://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/36px-Flag_of_Trinidad_and_Tobago.svg.png; sleep 1
wget -O Flag_of_Tunisia.png http://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/36px-Flag_of_Tunisia.svg.png; sleep 1
wget -O Flag_of_Turkey.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/36px-Flag_of_Turkey.svg.png; sleep 1
wget -O Flag_of_Turkmenistan.png http://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/36px-Flag_of_Turkmenistan.svg.png; sleep 1
wget -O Flag_of_Tuvalu.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/36px-Flag_of_Tuvalu.svg.png; sleep 1
wget -O Flag_of_Uganda.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/36px-Flag_of_Uganda.svg.png; sleep 1
wget -O Flag_of_Ukraine.png http://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/36px-Flag_of_Ukraine.svg.png; sleep 1
wget -O Flag_of_the_United_Arab_Emirates.png http://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/36px-Flag_of_the_United_Arab_Emirates.svg.png; sleep 1
wget -O Flag_of_the_United_Kingdom.png http://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/36px-Flag_of_the_United_Kingdom.svg.png; sleep 1
wget -O Flag_of_Tanzania.png http://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/36px-Flag_of_Tanzania.svg.png; sleep 1
wget -O Flag_of_the_United_States.png http://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/36px-Flag_of_the_United_States.svg.png; sleep 1
wget -O Flag_of_Uruguay.png http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/36px-Flag_of_Uruguay.svg.png; sleep 1
wget -O Flag_of_Uzbekistan.png http://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/36px-Flag_of_Uzbekistan.svg.png; sleep 1
wget -O Flag_of_Vanuatu.png http://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/36px-Flag_of_Vanuatu.svg.png; sleep 1
wget -O Flag_of_Venezuela.png http://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Flag_of_Venezuela_%28state%29.svg/36px-Flag_of_Venezuela_%28state%29.svg.png; sleep 1
wget -O Flag_of_Vietnam.png http://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/36px-Flag_of_Vietnam.svg.png; sleep 1
wget -O Flag_of_Yemen.png http://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/36px-Flag_of_Yemen.svg.png; sleep 1
wget -O Flag_of_Zambia.png http://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/36px-Flag_of_Zambia.svg.png; sleep 1
wget -O Flag_of_Zimbabwe.png http://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/36px-Flag_of_Zimbabwe.svg.png; sleep 1
